# prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# terminal settings for correct line wrapping
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ",*:U8=0"
set -g escape-time 10
